import { ActivityRepositoryInterface } from "../../domain/repositories/activity.repository.interface";
import {
  UserActivity,
  ActivityType,
} from "../../domain/entities/user-activity.entity";
import { ActivityDto } from "../dtos/activity.dto";
import { logger } from "../../common/logger";

export class ActivityService {
  constructor(private activityRepository: ActivityRepositoryInterface) {}

  async recordActivity(
    userId: string,
    type: ActivityType,
    description: string,
    metadata: Record<string, any> = {}
  ): Promise<ActivityDto> {
    logger.info(`Recording activity for user ${userId}: ${type}`);

    const activity = new UserActivity(
      "", // ID generated by DB
      userId,
      type,
      description,
      metadata,
      new Date()
    );

    const createdActivity = await this.activityRepository.create(activity);
    return this.mapToDto(createdActivity);
  }

  async getUserFeed(
    userId: string,
    limit: number,
    offset: number
  ): Promise<ActivityDto[]> {
    const activities = await this.activityRepository.findByUserId(
      userId,
      limit,
      offset
    );
    return activities.map(this.mapToDto);
  }

  async getAllActivities(
    limit: number,
    offset: number
  ): Promise<ActivityDto[]> {
    const activities = await this.activityRepository.findAll(limit, offset);
    return activities.map(this.mapToDto);
  }

  private mapToDto(activity: UserActivity): ActivityDto {
    return new ActivityDto(
      activity.id,
      activity.userId,
      activity.type,
      activity.description,
      activity.metadata,
      activity.createdAt
    );
  }
}
